name: Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup JDK${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Get Version
        id: mod_version
        run: echo "mod_version=""$(./gradlew printVersion | grep -E ^[0-9]+\.[0-9]+ -m 1)" >> $GITHUB_OUTPUT

      - name: Minecraft Version
        id: minecraft_version
        run: grep "minecraftVersion" gradle.properties -m 1 | sed "s/\s//g" >> $GITHUB_OUTPUT

      - name: Chmod Gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.mod_version.outputs.mod_version }}
          name: EnvironmentTech ${{ steps.mod_version.outputs.mod_version }} for ${{ steps.minecraft_version.outputs.minecraftVersion }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          artifacts: "build/libs"
          token: ${{ secrets.GITHUB_TOKEN }}
